psl_channel_fsm_main: remove FsmDbgEnableLoggingViaPlmLogLib call
* the define which should enable it was already commented out causing:
  [5/8] /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/qemux86_64-webos-linux/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-gcc -Dpalmsocket_EXPORTS -I/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/qemux86_64-webos-linux/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/qemux86_64-webos-linux/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/qemux86_64-webos-linux/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/include/public/palmsocket -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/qemux86_64-webos-linux/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/qemux86_64-webos-linux/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0=/usr/src/debug/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0                      -fdebug-prefix-map=/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/qemux86_64-webos-linux/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0=/usr/src/debug/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0                      -fdebug-prefix-map=/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/qemux86_64-webos-linux/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/recipe-sysroot=                      -fdebug-prefix-map=/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/qemux86_64-webos-linux/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/recipe-sysroot-native=   -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=/OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/qemux86_64-webos-linux/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/recipe-sysroot -Wno-deprecated-declarations -Wl,--no-undefined -DNDEBUG -fPIC -MD -MT CMakeFiles/palmsocket.dir/src/psl_channel_fsm_main.c.o -MF CMakeFiles/palmsocket.dir/src/psl_channel_fsm_main.c.o.d -o CMakeFiles/palmsocket.dir/src/psl_channel_fsm_main.c.o -c /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/qemux86_64-webos-linux/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/src/psl_channel_fsm_main.c
  /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/qemux86_64-webos-linux/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/src/psl_channel_fsm_main.c: In function 'psl_chan_fsm_new':
  /OE/build/luneos-kirkstone/webos-ports/tmp-glibc/work/qemux86_64-webos-linux/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/src/psl_channel_fsm_main.c:152:5: warning: implicit declaration of function 'FsmDbgEnableLoggingViaPmLogLib' [-Wimplicit-function-declaration]
    152 |     FsmDbgEnableLoggingViaPmLogLib(&fsm->base.base,
        |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>