CMakeLists.txt: build with -Wl,--no-undefined
* to catch undefined symbols during build instead of runtime like in:
  qemux86-64 ls-hubd[968]: /usr/bin/mojomail-imap: symbol lookup error: /usr/lib/libpalmsocket.so.2: undefined symbol: psl_chan_fsm_evt_dispatch_CONNECT

* current issues:
  /usr/src/debug/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/src/psl_channel.c:892: error: undefined reference to 'psl_chan_fsm_evt_dispatch_CONNECT'
  /usr/src/debug/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/src/psl_channel_fsm_crypto.c:2175: error: undefined reference to 'crypto_preprocess_READ'
  /usr/src/debug/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/src/psl_channel_fsm_crypto.c:2155: error: undefined reference to 'psl_chan_fsm_sched_fdwatch_completion_cb'
  /usr/src/debug/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/src/psl_channel_fsm_crypto.c:2155: error: undefined reference to 'psl_chan_fsm_sched_fdwatch_completion_cb'
  /usr/src/debug/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/src/psl_channel_fsm_crypto.c:930: error: undefined reference to 'psl_chan_fsm_sched_fdwatch_completion_cb'
  /usr/src/debug/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/src/psl_channel_fsm_crypto.c:921: error: undefined reference to 'psl_chan_fsm_sched_fdwatch_completion_cb'
  /usr/src/debug/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/src/psl_error_utils.c:504: error: undefined reference to 'ERR_GET_FUNC'
  /usr/src/debug/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/src/psl_error_utils.c:504: error: undefined reference to 'ERR_GET_FUNC'
  /usr/src/debug/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/src/psl_openssl_init.c:439: error: undefined reference to 'CRYPTO_get_lock_name'
  /usr/src/debug/libpalmsocket/2.0.0-33+gitAUTOINC+0319a6fba4-r0/git/src/psl_openssl_init.c:488: error: undefined reference to 'CRYPTO_get_lock_name'

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>